### Numpy is the numerical computing package in Python

In [1]:
import numpy as np

The import statement is used to import external libraries. All functions within the imported library are now accesible through that library's namespace. Since we imported numpy as "np", we can now access the functions within the Numpy library through: np.\<function name\>

In [2]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

The arange function takes in the "start" value, "stop" value, and the "step" size as inputs and returns an evenly spaced array. For more information, read the documentation: 

In [6]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : integer or real
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : integer or real, optional
    Spacing between values.  For any output `out`, this is the distance
  

In [12]:
np.linspace(0,0.9,10)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Above, we created a matrix with 3 rows and 4 columns. It has a shape of 3 x 4

In [5]:
arr.shape

(3, 4)

In [8]:
np.full_like(np.zeros(10), 10)

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [9]:
np.zeros(10) + 10

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

## Why use numpy?

Firstly, numpy provides access to efficient and optimized implementation of array handling operations. For instance, let's repeat the exercise from the previous notebook, where we created a list of 1000 elements and performed certain operations on each element.

In [15]:
%%timeit
x = []
for i in range(1000):
    x.append(i**2 + 0.5 * i + 2.5)

308 µs ± 3.56 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [63]:
%%timeit 
xn = np.arange(1000, dtype=np.float64)
xn = xn**2 + 0.5 * xn + 2.5

6.32 µs ± 50.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


<br/><br/>
Numpy is ~2 orders of magnitude faster!

The pure Python way of doing things is slower because Python is a dynamically typed language and the compiler may not implement memory optimizations such as loading up the array elements into memory before the operation is carried out.

But the numpy way of doing things is faster because the underlying code is written in C, and we get all the optimization that comes with having defined types and compiler optimizations with memory management. We also avoid the overheads that come with storing the data type and checking it before every operation is carried out, leading to much faster running code!

### Indexing in numpy

In [55]:
x = np.arange(5)

In [32]:
x

array([0, 1, 2, 3, 4])

In [33]:
print(x[0], x[1], x[2], x[3], x[4])

0 1 2 3 4


In [34]:
print(x[5])

IndexError: index 5 is out of bounds for axis 0 with size 5

#### Index 5 threw an error because our array has elements in the 0th, 1st, 2nd, 3rd, and 4th positions only. Remember, indexing in Python begins from 0

In [35]:
print(x[:])

[0 1 2 3 4]


In [39]:
print(x[-1], x[-2], x[-3], x[-4], x[-5])

4 3 2 1 0


Numpy slicing opperator is ":" the colon. Use the operator with the lower index and the higher index to access slices of the array

In [41]:
x[0:3]

array([0, 1, 2])

In [45]:
x[-3:]

array([2, 3, 4])

In [40]:
x[::-1]

array([4, 3, 2, 1, 0])

### Array operations

All operations on the numpy object are by default applied to every element in the array

In [56]:
x + 10

array([10, 11, 12, 13, 14])

In [57]:
x

array([0, 1, 2, 3, 4])

In [58]:
x = (x + 10) / 10

In [59]:
x

array([1. , 1.1, 1.2, 1.3, 1.4])

In [61]:
x[0] = x[0] * 5

In [62]:
x

array([5. , 1.1, 1.2, 1.3, 1.4])

### Exercise 03: Using both arange and linspace

1. Create an array of length 5, 10, 100, 1000 of equally spaced numbers between 0 and 1 
1. Create a 2 dimensional array, "arr", of shape 3x3, with the first row having all 1's, second row having all 2's, and the third row having all 3's
1. Access the diagonal elements of "arr" created above and multiply it by 10
1. Access the first column of "arr" and add it with the third column of "arr"